version: "3"

networks:
  app-tier:
    driver: bridge

services:
  boilerplate-api-pg:
    image: bitnami/postgresql
    networks:
      - app-tier
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=db_user
      - POSTGRESQL_PASSWORD=db_password
      - POSTGRESQL_DATABASE=my_database

  boilerplate-api-container:
    depends_on:
      - boilerplate-api-pg
    image: boilerplate-api-image
    networks:
      - app-tier
    ports:
      - 3333:3333
